version: '2'
services:
  web:
    build: .
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    links:
      - mysql:mysql
    volumes:
      - ./etc/apache2:/etc/apache2
      - ./var/log:/var/log
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
  redis:
    image: redis
    ports:
      - "6379:6379"
      - "6380:6380"
